### ISSUE TITLE
Install process for other VM systems

### ISSUE THREAD

**Issue by juchi** [open-orchestra/open-orchestra#452]
It would be nice to have an install procedure that's working for other VM systems such as LXC or Docker.
I'm mostly thinking about the provisionning issue but there may be other questions worth asking.

**Comment by nicolasThal** [comment]
We have already achieved the first step : the provisioning has been extracted to another repository to be more flexible : https://github.com/open-orchestra/open-orchestra-provision.

We are thinking about writting some documentation for the installation on other hypervisor

**Comment by nicolasThal** [comment]
This has been added to the roadmap
