### ISSUE TITLE
Caching CSS and JS library

### ISSUE THREAD

**Issue by itkg-yfarci** [open-orchestra/open-orchestra#549]
The Back Office uses lib JS or CSS who are never cached by the browser because a timestamp is present.

![capturendp](https://cloud.githubusercontent.com/assets/8710240/8541243/051fcd2a-248d-11e5-9cfe-650c725e848d.PNG)

**Comment by nicolasThal** [comment]
The timestamp is set to the deploy timestamp, this way, files will be cached between each deploy
