### ISSUE TITLE
Datepicker won't work with firefox

### ISSUE THREAD

**Issue by itkg-mraiffe** [open-orchestra/open-orchestra#719]
When I rollover a date field, datapicker doesn't appear with Firefox 41.0.1. It work correctly with Chrome.

**Comment by itkg-alavieille** [comment]
it's fix in this PR https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1320 and https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1302
