### ISSUE TITLE
Keyword created from dynamics attributes is store in db but does not appear in field

### ISSUE THREAD

**Issue by glenouvel** [open-orchestra/open-orchestra#760]
When I create a keyword from the dynamic attributes of my content, the keyword is registered but does not appear in the field. To see it you must refresh page

**Comment by itkg-ngilain** [comment]
Can't be reproduced on OO 1.1-ALPHA2

**Comment by nicolasThal** [comment]
The usecase here is a little bit tricky. I will emphasize @glenouvel description : 

In the project, we create keyword based on the attributes of the content.
To do so, we listen to the `CONTENT_UPDATE` event.
This event is launched after the form is bind.
When the form is displayed, the new keywords (created on the listener) does not appear.
When we reload the page, the keyword appear

**Comment by itkg-nanne** [comment]
This issue is fixed in 1.1
