### ISSUE TITLE
field type oo_tinymce in a collection field doesn't work

### ISSUE THREAD

**Issue by glenouvel** [open-orchestra/open-orchestra#814]
When i create a field_type collection which contains 3 fields : 
    -  field type text
    -  field type text area
    -  field type oo_tinymce.

TinyMce is init but addPrototype is lunch after.
Replacement textarea of TinyMce by skin tinyMce is KO

**Comment by itkg-nanne** [comment]
fixed in :
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/135
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1396
