### ISSUE TITLE
Site configuration, meta_index and meta_follow doesn't work

### ISSUE THREAD

**Issue by itkg-mraiffe** [open-orchestra/open-orchestra#815]
Hello,
If I understand the behaviour of meta_index and meta_follow (site configuration), if I let them to "off" some meta will appear in the <head> of the page :  <meta name="robots" content="noindex,nofollow">
If I switch on "On" or "Off" nothing appends.

**Comment by nicolasThal** [comment]
I have made the change in the layout : https://github.com/open-orchestra/open-orchestra-front-bundle/pull/138.

@nbouquet do we also need to change the base value of those fields when we create a node ?

**Comment by itkg-ngilain** [comment]
I think there's a bigger problem here. As mentionned in https://github.com/open-orchestra/open-orchestra-docs/blob/master/en/user_guide/websites_creation.rst the site default values are overwritten by the node settings. But this mechanism doesn't seems to be correctly implemented, so I would say that only the node settings are used.

**Comment by nicolasThal** [comment]
@itkg-ngilain I think we should continue the discussion on the issue :).

The fallback is done at the node creation, in the BackofficeBundle\NodeManager we copy the value from the site

**Comment by itkg-ngilain** [comment]
you're right, my bad :)
