### ISSUE TITLE
Can't manage user rights in the user creation form

### ISSUE THREAD

**Issue by itkg-mraiffe** [open-orchestra/open-orchestra#817]
Actually the user creation form haven't the "Right form" tab. You must return to the user list and re-edit the user to see it. It's not user friendly and there isn't a message to indicate this.

**Comment by itkg-mraiffe** [comment]
After a little talk with @nicolasThal. Maybe the solution is to use the same behavior as the content creation form : When the user save the new content, the popin closed automaticaly.

**Comment by Thiblef** [comment]
fixed in:
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1408
