### ISSUE TITLE
Can we used it in existing project 

### ISSUE THREAD

**Issue by speeeeeed2006** [open-orchestra/open-orchestra#912]
Hello just to know, can we used in a existing project ?
Thank you.

**Comment by alavieille** [comment]
Open orchestra is split in different bundles to be used in other symfony application and also used just a part of cms .so yes you can used it on other application with may be some adjustments. Furthermore about licence, the project is under apache2, so any problem to use it in other project

Like for the others bundles of symfony you should add bundles in appKernel and add routing. For the configuration you can look the config.yml to take the needed configuration.

Finally, you should take grunt task contained in grunt folder used to compile the different javascript and css by the back office.
